# Generated by Django 4.1.5 on 2023-01-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
